### PR TITLE
Bring forward plugin load errors

### PR DESCRIPTION
**Pull request by pi-r-p**
After Warp10 2.0.1 update with an old config file, the quantum loading error is really not obvious.
These small changes will facilitate the admin job.

### CODE REVIEW

**Comment by pi-r-p** [comment]
moved plug in and extension errors to a logger, add stdout appender to rootlogger.

**Comment by pi-r-p** [comment]
double appender lead to double logs as we also log stdout. corrected.

**Comment by hbs** [comment]
Is this PR still to be considered for merging?

**Comment by pi-r-p** [comment]
Yes, but not complete. Need a return value in case of service launch error. I must end the job.

**Pull request merged**
