### PR TITLE
Fixed ECDH for curve25519 so it uses X25519

### PR DESCRIPTION
**Pull request by hbs**

### CODE REVIEW

**Review by pi-r-p — APPROVED** [review]

**Review by stggn — COMMENTED** [review]
With ECDH and 'curve25519' the secrets are now different, while with other curves they are identical:

```
//'c2pnb208w1' 'curve' STORE 
'curve25519' 'curve' STORE
$curve ECGEN
ECPUBLIC 'pub1' STORE
ECPRIVATE 'priv1' STORE

$curve ECGEN
ECPUBLIC 'pub2' STORE
ECPRIVATE 'priv2' STORE

$priv1 $pub2 ECDH
$priv2 $pub1 ECDH
```

**Comment by hbs** [comment]
> With ECDH and 'curve25519' the secrets are now different, while with other curves they are identical:
> 
> ```
> //'c2pnb208w1' 'curve' STORE 
> 'curve25519' 'curve' STORE
> $curve ECGEN
> ECPUBLIC 'pub1' STORE
> ECPRIVATE 'priv1' STORE
> 
> $curve ECGEN
> ECPUBLIC 'pub2' STORE
> ECPRIVATE 'priv2' STORE
> 
> $priv1 $pub2 ECDH
> $priv2 $pub1 ECDH
> ```

This is the reason for this PR, the DH done using curve25519 was incorrect until this PR.

**Comment by hbs** [comment]
PTAL had to fix public key computation from private key when using curve25519 as it was not using the correct approach.

**Review by stggn — APPROVED** [review]
ECDH doc is updated

**Pull request merged**
