### PR TITLE
Added options to output GTS list as WarpScript

### PR DESCRIPTION
**Pull request by hbs**

### CODE REVIEW

**Comment by pi-r-p** [comment]
A few questions about the functions:
- Is there a good reason not to build a list of GTS ? maxdepth can be reached easily.
```
[]
'xxx' UNWRAP +!
'yyy' UNWRAP +!
```
- if clearwarscript must be readable, {}= must not be escaped (just as standard FIND), and it should be a single line followed by PARSE (no SWAP nor +)

**Comment by hbs** [comment]
The format is identical to the one produced in the `.info` file generated along HFiles, compatibility is key.

**Comment by pi-r-p** [comment]
If so, and if needed, should it also have a fake count ?
sb.append(" # 0 0");

**Comment by hbs** [comment]
Count is a comment, not ever parsed

**Review by pi-r-p — APPROVED** [review]

**Pull request merged**
