### PR TITLE
Comments parsing

### PR DESCRIPTION
**Pull request by hbs**

### CODE REVIEW

**Review by pi-r-p — CHANGES_REQUESTED** [review]
cannot work as it is, you can have comments within strings.
`"  /* test */%0A  string"`  leads to 3 spaces before and after tests.

**Comment by hbs** [comment]
Fixed space handling around /* and */

**Review by pi-r-p — CHANGES_REQUESTED** [review]
not ok for this test:

```
CLEAR 
41 /* "x": true, */ 42 /* "x": true, */ 43 /**/ 45 
45 == ASSERT
43 == ASSERT 
42 == ASSERT 
41 == ASSERT 

```

**Comment by hbs** [comment]
Will be implemented by #1250

**Pull request closed without merging**
