### PR TITLE
Fixes #1268 and a bug in the values output by VALUESPLIT

### LINKED ISSUE #1268: VALUESPLIT does not split boolean values as expected
Hi there,

`VALUESPLIT` does not split series with booleans as it did  for other values:

```
NEWGTS
1000000 NaN NaN NaN true ADDVALUE
2000000 NaN NaN NaN false ADDVALUE
3000000 NaN NaN NaN true ADDVALUE
4000000 NaN NaN NaN true ADDVALUE
5000000 NaN NaN NaN false ADDVALUE
6000000 NaN NaN NaN false ADDVALUE
7000000 NaN NaN NaN false ADDVALUE
8000000 NaN NaN NaN true ADDVALUE
9000000 NaN NaN NaN false ADDVALUE
10000000 NaN NaN NaN true ADDVALUE
'split-label'
VALUESPLIT 
```

It would output 7 GTS whereas I expected only 2 (all the truthy in one GTS, all the falsy in one GTS). Seems it regroups by consecutives values only, not globally

whereas :

```
NEWGTS
'test name' RENAME
{ 'label0' '42' 'label1' 'foo' } RELABEL
100  NaN NaN NaN 10 ADDVALUE
400  NaN NaN NaN 10 ADDVALUE
500  NaN NaN NaN  6 ADDVALUE
700  NaN NaN NaN  6 ADDVALUE
800  NaN NaN NaN  6 ADDVALUE
900  NaN NaN NaN  6 ADDVALUE
1000 NaN NaN NaN  4 ADDVALUE
1100 NaN NaN NaN  4 ADDVALUE
200  NaN NaN NaN 10 ADDVALUE
300  NaN NaN NaN 10 ADDVALUE
'split-label'
VALUESPLIT
```

will output 3 GTS (one for 10, one for 6, one for 4) as expected.

Thanks

### PR DESCRIPTION
**Pull request by hbs**

### CODE REVIEW

**Review by pi-r-p — CHANGES_REQUESTED** [review]
This fixes VALUESORT, but this is not efficient for VALUESPLIT. 

Splitting a boolean gts do not need to sort input. Just create two empty gts, iterate on each input value to populate these gts, then keep non empty ones.


test code:

```
NEWGTS
1 1e6 TOLONG <%
  'v' STORE
  [ $v true ] ADDVALUE
%> FOR 
[ NOW false ] ADDVALUE
'input' STORE

'split' CHRONOSTART
$input 'x' VALUESPLIT DROP 
'split' CHRONOEND 

CHRONOSTATS
```

(should take 1 second, not 20)

**Review by pi-r-p — CHANGES_REQUESTED** [review]
60ms instead of 28s.
Sorting booleans can be done with the same strategy/code: fast boolean split then merge both. booleanSplit can be a new method in GTSHelper, used by both functions.

**Comment by pi-r-p** [comment]
```
[
  $input false ==
  $input true ==
] MERGE
```
takes 150ms (one million value input)  (28s for VALUESORT)

**Comment by hbs** [comment]
sort is stable, MERGE is not

**Review by pi-r-p — APPROVED** [review]

**Review by steven-gueguen — APPROVED** [review]

**Pull request merged**
