### PR TITLE
Cleaned up key definitions

### PR DESCRIPTION
**Pull request by hbs**
This is a preliminary work to the refactoring of bootstrap in warp10.sh

### CODE REVIEW

**Comment by pi-r-p** [comment]
To discuss: why removing keys from 00-secrets.conf ?  The file name is pretty clear, and this file must remain portable between all the Warp10 configurations to share tokens.

**Comment by hbs** [comment]
Keys are still in 00-secrets, their default value is simply a reference to another generic name which can be generated easily without modifying existing files. Should the user wish to propagate the actual values in 00-secrets they can still do so.

**Comment by hbs** [comment]
> To discuss: why removing keys from 00-secrets.conf ? The file name is pretty clear, and this file must remain portable between all the Warp10 configurations to share tokens.

They are not removed from this file.

**Comment by hbs** [comment]
> So, you plan to update io.warp10.GenerateCryptoKey#fillConfigFile to detect keys and not `= hex:hhhh` in a later PR ?

My intent is to modify the way the keys are generated, we should not attempt to modify a file, rather create a new one and let users decide if they want to keep the definitions in that new file or move them to 00-secrets (or rename the file 00-secrets if that makes sense).

**Review by pi-r-p — APPROVED** [review]

**Pull request merged**
