### PR TITLE
Fixed sanitizeString for cases when quote is followed by a wsp inside a string

### PR DESCRIPTION
**Pull request by hbs**

### CODE REVIEW

**Comment by hbs** [comment]
hasSep is actually useless since it always has the same value as instring, will update the PR accordingly

**Comment by hbs** [comment]
PTAL

**Comment by pi-r-p** [comment]
The failure is also be very weird, because it fails at symbol = stmt.substring(1, stmt.length() - 1);
```
" "" "
```
leads to:
`Exception at '"%20"" =>"<=' in section [TOP] (begin 1, end 0, length 1)`

**Comment by hbs** [comment]
> The failure is also be very weird, because it fails at symbol = stmt.substring(1, stmt.length() - 1);
> 
> ```
> " "" "
> ```
> 
> leads to: `Exception at '"%20"" =>"<=' in section [TOP] (begin 1, end 0, length 1)`

Added a check to ensure strings are enclosed in quotes and not just a quote

**Review by pi-r-p — APPROVED** [review]
leads to unknown function `"` in audit mode. consistent.

**Pull request merged**
